services:
  mongodb:
    image: mongo:latest
    container_name: mongo-archive
    volumes:
      - ../../../mongodb/archive/:/data/db/
    ports:
      - '27017:27017'

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:0.13.3
    network_mode: bridge
    ports:
      - "127.0.0.1:4510-4559:4510-4559"  # external service port range
      - "127.0.0.1:4566:4566"            # LocalStack Edge Proxy
    environment:
      - DEBUG=${DEBUG-}
      - DATA_DIR=${DATA_DIR-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - AWS_DEFAULT_REGION=eu-west-1
      - EDGE_PORT=4566
      - SERVICES=lambda,s3,sqs,cloudformation,sts,iam,cloudwatch,events
      - DOCKER_HOST=unix:///var/run/docker.sock
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - HOSTNAME_EXTERNAL=host.docker.internal
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
